server:
  port: 52014

filePath: E:\stm32 project\k210\k210-web\public
value: true



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openmv?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    #    解决升级Spring Boot2.6后,因依赖循环引用导致启动时报错的问题
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.k210.licj.k210.pojo    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
